cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'

brew 'coreutils'
brew 'findutils'
brew 'wget', args: ['enable-iri']
brew 'homebrew/dupes/grep'
brew 'vim'
brew 'git'
brew 'hub'
brew 'ssh-copy-id'
brew 'node'
brew 'tree'
brew 'htop'
brew 'imagemagick'
brew 'jq'
brew 'readline'
brew 'postgresql'
brew 'unrar'
brew 'watch'
brew 'zsh'

brew 'php71', args: ['with-intl']
brew 'php71-xdebug'
brew 'composer'

cask 'dropbox'
cask '1password'
cask 'alfred'
cask 'virtualbox'
cask 'vagrant'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'sequel-pro'
cask 'phpstorm'
cask 'docker'
cask 'spotify'