cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'findutils'
brew 'wget', args: ['enable-iri']
brew 'grep'
brew 'vim'
brew 'git'
brew 'hub'
brew 'ssh-copy-id'
brew 'autojump'
brew 'direnv'
brew 'node'
brew 'htop'
brew 'readline'
brew 'postgresql'
brew 'unrar'
brew 'watch'
brew 'zsh'
brew 'kubectl'

brew 'php@7.2', args: ['with-intl']
brew 'composer'

brew 'docker'
brew 'docker-machine'
brew 'docker-compose'

cask 'dropbox'
cask '1password'
cask 'alfred'
cask 'virtualbox'
cask 'vagrant'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'sequel-pro'
cask 'phpstorm'
#cask 'docker'
cask 'spotify'
cask 'google-cloud-sdk'
cask 'little-snitch'
cask 'sketch'
cask 'caffeine'
cask 'insomnia'
